### ISSUE TITLE
Feature Request: B Rank Image Pop up or Markers for the potential spawns

### ISSUE THREAD

**Issue by Shiichibukai** [SheepGoMeh/HuntBuddy#15]
Like the title says, would it be possible to have Hunt Buddy show a pop up image of the potential spawn points for the B Ranks? Maybe namely only the ShB/EW ones - or markers on the map if the game even allows multiple markings like that~

**Comment by PrincessRTFM** [comment]
Map markers in the game are unlikely because, while circle-area markers can seemingly coexist, the minimap won't show them. The method used to place _that_ marker is the same one as control-right-clicking on the large map, which only allows a single marker. If I can find a way to make #16 work then this may be doable. I doubt that a popup image of spawn points will be particularly viable either way since that would have to including in the plugin separately, whereas the mob images are (IIRC) taken from the game's own files.

**Comment by PrincessRTFM** [comment]
Sheep and I have talked and we're just not willing to do this one, sorry. It'd take a _lot_ of work to add all of the location data, require a _major_ rework of the internals to support having multiple locations for a single target, need a hack to even place the markers in the first place, and it'd highlight anywhere from a full quarter to literally the _entire_ map, depending on the mark.

My recommendation: look at an online map, pick out a heavy region, and fly over it until you get the message about sensing your mark. Maybe grab the AetherCompass plugin too, it can point you directly to the (nearby only, game data limitation) mob once you're close enough for it to be loaded on your client - which is like 150 yalms, horizontally.

If you have a second screen, you can pull up the map on that to look between it and your game.
