### ISSUE TITLE
'/phb next' command stops working

### ISSUE THREAD

**Issue by AKA-Syenite** [SheepGoMeh/HuntBuddy#20]
After a few successful hunts, the command no longer places a marker, or sends a message in chat, despite there being incomplete bills. '/phb reload', changing maps, and restarting the game did not fix the issue.

v1.0.1.0 is installed

**Comment by PrincessRTFM** [comment]
Do you have any weekly bills in your possession when the command stop working? If so, can you complete (or discard) those and try again?

**Comment by AKA-Syenite** [comment]
After discarding the weekly bills, the command worked a few more times, then stopped again.

**Comment by PrincessRTFM** [comment]
Hm. Okay, so it's not what I was thinking about then. I'll look into it, once I stop having 85% packet loss and can actually get on and play to track this down.

**Comment by PrincessRTFM** [comment]
I can confirm that having a weekly bill can cause this issue, and I'm pretty sure it's because the plugin stops when it finds the weekly target but then _doesn't_ have a location for it, so it doesn't have anything to open your map to.

**Comment by PrincessRTFM** [comment]
Found the bug. Turns out I'm a fucking idiot. I was [using a greater-than check](https://github.com/SheepGoMeh/HuntBuddy/blob/5a92e0e104839c30eaf398790dee32b793c3c53e/HuntBuddy/Plugin.cs#L197) where I should've used a greater-or-equal check. Well, I've at least done some more work to make sure that elite marks don't break anything. I'll push this in a few once I've finished testing.

**Comment by PrincessRTFM** [comment]
Solved in [45804a](https://github.com/SheepGoMeh/HuntBuddy/commit/45804a5524fd0c6e1fb8e4dbc17c99755248e4d1). As soon as [the PR](https://github.com/goatcorp/DalamudPluginsD17/pull/2071) is merged, just update and it'll work properly.
