### ISSUE TITLE
No teleport option for daily hunts

### ISSUE THREAD

**Issue by graphicschyk** [SheepGoMeh/HuntBuddy#45]
Gatling is a B-rank. B-ranks do not have locations provided by the plugin, because they can spawn in multiple locations, often covering at least half the map zone. Acquire daily hunt bills and their targets will have the buttons.

_Originally posted by @PrincessRTFM in https://github.com/SheepGoMeh/HuntBuddy/issues/43#issuecomment-2218838144_

Yes, I clicked on the wrong one for that screen shot. Here is my screen from today:
![image](https://user-images.githubusercontent.com/175161059/347594414-8fa038eb-46ba-444b-87d0-30c355a5a0dd.png)

My map only has the small icons next to the location names.
 The hunts in current area  still looks the same way it did yesterday. No images and no teleport options.
![image](https://user-images.githubusercontent.com/175161059/347594979-ff0e75ba-11b1-4049-814d-2b8fb5ef1242.png)

**Comment by graphicschyk** [comment]
![image](https://github.com/SheepGoMeh/HuntBuddy/assets/175161059/c8a5726e-d213-4207-83fa-7ac8eb046d48)
![image](https://github.com/SheepGoMeh/HuntBuddy/assets/175161059/fdd802e2-6a42-4df5-bfaa-cecda664cf28)

Trying again since images didn't load.

**Comment by graphicschyk** [comment]
If it's not broken can you tell me how to make it so the hunts in current area shows me the same info others have where it marks them on the map?

**Comment by PrincessRTFM** [comment]
As you can see at the top of the main window, ARR hunts are not supported. We do not provide locations for them. Frankly, I'm surprised that they're showing up in the local hunts window at all, since they aren't _supposed_ to.

The purpose of HuntBuddy is to collect hunt marks from the _three_ daily bills in each of the post-ARR expansions into a single interface, so that you don't need to check three different bill stacks to see if you have any hunts left in a particular zone, from the total of _fifteen_ that you receive. In ARR, you have one stack of five, and two or three of those are always FATE targets, which don't even exist until the FATE is active. As a result of this, we - the developers - decided that ARR hunt marks will not be supported.
