### ISSUE TITLE
Automatically remove map marker after hunt for mob has completed

### ISSUE THREAD

**Issue by pkly** [SheepGoMeh/HuntBuddy#50]
Hello.

It seems after finishing the daily hunt for a mob in a zone the marker stays until removed by player or changed by selecting another target. Since you don't want to implement multiple markers, would you at least consider adding code that'd remove a marker on the current target once enough has been killed (and then maybe another option to enable next marker in zone based on distance to player?)

Thanks in advance, great plugin

**Comment by PrincessRTFM** [comment]
It's your map flag, the one you can place with control-rightclick. That's why we can't do multiple markers, you only have one flag. This also means we're not going to remove it, since we have no way of knowing if you've placed it manually or not.

If it helps, you can install [TinyCommands](https://github.com/PrincessRTFM/TinyCommands) and use the provided `/clearflag` command in a macro to make it easier.
